---
title: "Reprodutibilidade computacional em Ecologia e Evolução"
---

| Dia | Data | Tópico | Descrição | Roteiros e códigos | Slides | Leituras |
|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
| 1 | 10/08 | Ciência Aberta \| Reprodutibilidade computacional \| Apresentação da disciplina | O movimento da ciência aberta, ferramentas computacionais para garantir um trabalho reprodutivo, dinâmica da disciplina | [💻](https://lab-mmm.github.io/Disciplina_Reprodutibilidade_Computacional_Ciencia_Aberta/aulas/01_ciencia_aberta/) |  | [📚](https://lab-mmm.github.io/Disciplina_Reprodutibilidade_Computacional_Ciencia_Aberta/aulas/01_ciencia_aberta/#leituras-recomendadas) |
| 2 | 11/08 | Organização do diretório de trabalho e scripts \| Introdução ao controle de versão | Conhecendo os caminhos no computador \| Pequena introdução ao terminal \| Estrutura hierárquica de diretórios \| Introdução ao Git como ferramenta para controle de versão | [💻](https://lab-mmm.github.io/Disciplina_Reprodutibilidade_Computacional_Ciencia_Aberta/aulas/03_organizacao_local_caminhos/) | [📽](https://lab-mmm.github.io/Disciplina_Reprodutibilidade_Computacional_Ciencia_Aberta/aulas/03_organizacao_local_caminhos/slides.html#/title-slide) |  |
| 3 | 12/08 | Repositórios locais e remotos \| Integração com IDE (RStudio) \| Práticas em controle de versão | Utilizando o Git e o Github de maneira integrada através do RStudio \| Ações básicas para versionar seu repositório | [💻](https://lab-mmm.github.io/Disciplina_Reprodutibilidade_Computacional_Ciencia_Aberta/aulas/05_intro_reprodutibilidade/) | [📽](https://lab-mmm.github.io/Disciplina_Reprodutibilidade_Computacional_Ciencia_Aberta/aulas/05_intro_reprodutibilidade/slides.html#/title-slide) | 📚 |
| 4 | 13/07 | Trabalho colaborativo \| Literate programming \| Revisão de código | Utilizando branches, forks, issues e resolvendo conflitos em trabalhos colaborativos \| Utilizando markdown para produção de relatórios científicos, manuscritos e sites \| Rodada de revisão de código entre participantes | [💻](/aulas/Aula1_phylo_trees.html) | 📽 | 📚 |
| 5 | 14/07 | Manejando versões de pacotes \| Organizando o fluxo de trabalho \| Finalização | Utilização de ferramentas para manejar versões de pacotes e organização de fluxos de trabalho (renv e targets) | [💻](/aulas/Aula1_phylo_trees.html) | 📽 | 📚 |
